name: CI
on:
  pull_request:
    branches: [develop]
  push:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Node JS
        uses: actions/setup-node@v1
        with:
          node-version: "16.17.0"
      - run: npm install
      - run: npx prettier --write .
      - name: Run linters
        uses: wearerequired/lint-action@v2
        with:
          eslint: true
          prettier: true
      - run: npm run test:headless
      - name: Build Project
        if: github.event_name == 'push'
        run: npm run build
      - name: Deploy to Staging
        if: github.event_name == 'push'
        uses: dswistowski/surge-sh-action@v1
        with:
          domain: "married-scalewwwww.surge.sh"
          project: "./dist/todo-items-project"
          login: ${{ secrets.surge.SURGE_LOGIN }}
          token: ${{ secrets.surge.SURGE_TOKEN }}
