name: CI
on:
  pull_request:
    branches: [develop]
  push:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Node JS
        uses: actions/setup-node@v1
        with:
          node-version: '16.17.0'
      - run: npm install
      - name: Run linters
        uses: wearerequired/lint-action@v2
        with:
          eslint: true
          prettier: true
      - run: npm run test:headless
      - name: Build Project
        if: github.event_name == 'push'
        run: npm run build
      - run: npm install -g surge
        if: github.event_name == 'push'
      - name: Deploy to Staging
        if: github.event_name == 'push'
        run: surge ./dist/todo-items-project married-scalewwwww.surge.sh --token ${{ secrets.SURGE_TOKEN }}
